# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5571320f406480bd8573d58fa98ffea8f6dffe363b67db193832bbcd89d2d9b65893b3db5aa48cd776edbbe1a5001f8bdc3fddac71e9a8546e351c32d43ba065

test:
  secret_key_base: 75b34e8cff780943ce4e55b69fa44d4dadb1501067f11f02a53b08c0be7cfa489fd92637179e77a6e280f8c134fe840baa30a35e6079dea295140cbb1889b463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
